# Generated by Django 2.2 on 2020-02-08 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('clasemodelo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bases.ClaseModelo')),
                ('descripcion', models.CharField(help_text='Descripcion de la Categoria', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
            bases=('bases.clasemodelo',),
        ),
    ]
