# Generated by Django 2.2 on 2020-02-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'Marcas'},
        ),
    ]
