# Generated by Django 2.2 on 2020-02-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20200219_0323'),
        ('inv', '0004_auto_20200215_1733'),
    ]

    operations = [
    ]
